version: '3'

services:
  dynamodb-local-testing:
    image: amazon/dynamodb-local:2.3.0
    container_name: dynamodb-local-testing
    ports:
      - '8000:8000'
    environment:
      - AWS_ACCESS_KEY_ID=1
      - AWS_SECRET_ACCESS_KEY=2
      - AWS_DEFAULT_REGION=localhost
