import os

from dotenv import load_dotenv

load_dotenv(dotenv_path=".env.test")

AWS_REGION = os.environ.get("AWS_REGION")

THING_PAYLOADS_DB_NAME = os.environ.get("THING_PAYLOADS_DB_NAME")
QUEUE_WAIT_SECONDS = int(os.environ.get("QUEUE_WAIT_SECONDS"))
THINGS_REPORT_JOB_QUEUE = os.environ.get("THINGS_REPORT_JOB_QUEUE")
THINGS_REPORT_JOB_DLQ = os.environ.get("THINGS_REPORT_JOB_DLQ")
THINGS_REPORT_ARCHIVE_JOB_QUEUE = os.environ.get("THINGS_REPORT_ARCHIVE_JOB_QUEUE")
THINGS_REPORT_JOB_FILE_PATH_PREFIX = os.environ.get(
    "THINGS_REPORT_JOB_FILE_PATH_PREFIX"
)
THINGS_REPORT_JOB_BUCKET_NAME = os.environ.get("THINGS_REPORT_JOB_BUCKET_NAME")

THING_PAYLOADS_SERVICE_HOST = os.environ.get("THING_PAYLOADS_SERVICE_HOST")
THING_PAYLOADS_SERVICE_PORT = os.environ.get("THING_PAYLOADS_SERVICE_PORT")
THING_PAYLOADS_SERVICE_URI = os.environ.get("THING_PAYLOADS_SERVICE_URI")
THING_PAYLOADS_SERVICE_URL = f"http://{THING_PAYLOADS_SERVICE_HOST}:{THING_PAYLOADS_SERVICE_PORT}/{THING_PAYLOADS_SERVICE_URI}"
